export { default as Navbar } from './Navbar';
export { default as Intro } from './Intro';
export { default as Events } from './Events';
export { default as Blog } from './Blog';
export { default as SdgsGoals } from './SdgsGoals';
export { default as Footer } from './Footer';
export { default as SEO } from './SEO';
export { default as Head } from './Head';
export { default as Hero } from './Hero';
