import type { NextPage } from 'next'
import Head from 'next/head'
import { Intro, Navbar } from '@components/common'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>SDGS FUPRE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="w-full">
        <Navbar />
      </header>
      <main className="w-full">
        <Intro />
      </main>
      {/*  <footer className={styles.footer}>

      </footer> */}
    </div>
  );
}

export default Home
